### PR TITLE
install-drill-on-dataproc-in-distributed-mode

### PR DESCRIPTION
**Pull request by mohamedkashifuddin**
### This pull request contains the instructions to install drill on gcp dataproc
---
1. This is a documentation to install drill on gcp. 
2. This script installs drill on dataproc  as distributed mode with the help of automation scripts.

### CODE REVIEW

**Comment by luocooong** [comment]
@mohamedkashifuddin Thank you for that great contribution.
@paul-rogers Could we provide any suggestions for the auto-script file?

**Comment by luocooong** [comment]
@mohamedkashifuddin I recommend creating a new child chapter (parent chapter is `Install Drill`) : Extended. Then move `Drill-on-YARN` into the chapter and record this document in the chapter.

**Comment by paul-rogers** [comment]
For now, I suggest just creating the chapter, and move this file there. We can move DoY later, let's not complicate this one.

The general idea is that we want to provide this great info, but create a bit of a separation between the core material that the Drill team can maintain, and the community contributions, which broaden Drill's appeal, but that the core team is not set up to maintain.

We'd move DoY there because none of the current contributors have a Hadoop cluster available, and YARN is now somewhat dated.

In the title, change "install-dril-on..." to "install-drill-on", (spelling).

**Comment by mohamedkashifuddin** [comment]
Hi @luocooong @paul-rogers I have changed  title  "install-dril-on..." to "install-drill-on"  and its already moved under individual  child chapter  under (parent chapter is Install Drill), Please let me know if any changes needed I will do it.  
image

**Review by luocooong — APPROVED** [review]
LGTM. +1

**Pull request merged**
